const items = [
    {
        "id": 1,
        "category": 1,
        "img": "media/goods/HEALTH_Apple 蘋果_Apple Watch Series 5.png",
        "品牌": "Apple 蘋果",
        "name": "Apple Watch Series 5",
        "功能": "GPS/GNSS 定位系統、指南針\r\r\n氣壓高度計、加速度計\r\r\n第 2 代光學心率感測器、環境光度感測器\r\r\n全球緊急電話2、SOS 緊急服務5\r\r\n具備跌倒偵測功能\r\r\n揚聲器、麥克風\r\r\nApple pay",
        "特色": "電子心率感測器",
        "適用族群": "老少咸宜皆可",
        "price": 17900,
        "產品資訊連結": "https://support.apple.com/kb/SP808?viewlocale=zh_TW&locale=zh_TW",
        "like" : 1
    },
    {
        "id": 2,
        "category": 1,
        "img": "media/goods/HEALTH_MI 小米_AMAZFIT 米動手錶 青春版.png",
        "品牌": "MI 小米",
        "name": "AMAZFIT 米動手錶      青春版",
        "功能": "續航 45 天\r\r\n採用 GPS + GLONASS 雙模定位方式\r\r\n全程監測心率變化，運動量達不達標\r\r\n具備氣壓計跟指南針\r\r\n不掏手機，即時訊息直接看\r\r\n來電提醒、鬧鈴提醒、久坐提醒",
        "特色": "搭配小米運動app",
        "適用族群": "老少咸宜皆可",
        "price": 1995,
        "產品資訊連結": "https://www.mi.com/tw/amazfit-bip/",
        "like" : 2
    },
    {
        "id": 3,
        "category": 1,
        "img": "media/goods/HEALTH_SAMSUNG 三星_ Galaxy Fit智慧手環.png",
        "品牌": "SAMSUNG 三星",
        "name": " Galaxy Fit智慧手環",
        "功能": "擁有運動偵測、壓力管理，與訊息回應功能，採用可拆式錶帶設計，並且能與 iOS 10.0 或 Android 5.0 系統版本以上的裝置搭配使用；此外，支援心率偵測、睡眠監測、NFC 無線充電等。",
        "特色": "心率偵測\r\r\n睡眠監測\r\r\n訊息快速回應\r\r\n自動運動偵測\r\r\n智慧壓力管理",
        "適用族群": "老少咸宜皆可",
        "price": 2990,
        "產品資訊連結": "https://www.samsung.com/tw/watches/galaxy-fit/galaxy-fit-silver-sm-r370nzsabri/",
        "like" : 3
    },
    {
        "id": 4,
        "category": 1,
        "img": "media/goods/HEALTH_ASUS 華碩_慧電子門鎖 (DL101).png",
        "品牌": "ASUS 華碩",
        "name": "慧電子門鎖 (DL101)",
        "功能": "全球唯一防入侵門鎖，企圖橇鎖立即觸發警報\r\r\n輕鬆上鎖設定，自動啟動安全防護系統\r\r\n多功能四合一開鎖（鑰匙、觸控密碼、NFC、App遠端無線）\r\r\n緊急狀況下，使用預先設定的特殊密碼開鎖，系統立刻以訊息警示家人\r\r\n智慧App 排程設定情境控制隨心所欲",
        "特色": "多功能四合一開鎖（鑰匙、觸控密碼、NFC、App遠端無線）",
        "適用族群": "老少咸宜皆可",
        "price": 9990,
        "產品資訊連結": "https://www.asus.com/tw/Internet-of-Things/ASUS-SmartHome-Smart-Door-Lock-DL101/",
        "like" : 0
    },
    {
        "id": 5,
        "category": 1,
        "img": "media/goods/HEALTH_ASUS 華碩_智慧插座SmartHome Meter Plug MW100.png",
        "品牌": "ASUS 華碩",
        "name": "智慧插座 \r\r\nSmartHome Meter Plug MW100",
        "功能": "App內建排程功能，並可即時或定時開關電器\r\r\n實體電源開關按鍵\r\r\n過載自動斷電，防止電線走火\r\r\nZigbee無線信號，延伸連線範圍廣\r\r\n一鍵連結智慧管家，簡易方便\r\r\n搭配華碩智慧周邊裝置，情境運用更多元\r\r\n本產品需搭配華碩智慧管家(HG100)，方能創造居家專屬智慧連動情境",
        "特色": "遠端遙控開關電器，電量監控節能省電",
        "適用族群": "老少咸宜皆可",
        "price": 1490,
        "產品資訊連結": "https://www.asus.com/tw/Internet-of-Things/ASUS-SmartHome-Meter-Plug-MW100/",
        "like" : 0
    },
    {
        "id": 6,
        "category": 1,
        "img": "media/goods/HEALTH_ASUS 華碩_智慧警報器SmartHome Siren AS101.png",
        "品牌": "ASUS 華碩",
        "name": "智慧警報器 \r\r\nSmartHome Siren AS101",
        "功能": "透過App可與周邊智慧安全產品連動，專屬保全系統\r\r\n手機即時異常通知\r\r\n低功耗及App低電量警示\r\r\n一鍵連結智慧管家，省時方便\r\r\n本產品需搭配華碩智慧管家(HG100)，方能創造居家專屬智慧連動情境",
        "特色": "透過燈光、警報聲響和訊息通知，意外狀態即時警示",
        "適用族群": "老少咸宜皆可",
        "price": 1590,
        "產品資訊連結": "https://www.asus.com/tw/Internet-of-Things/ASUS-SmartHome-Siren-AS101/",
        "like" : 99
    },
    {
        "id": 7,
        "category": 1,
        "img": "media/goods/HEALTH_searchingc_Reston 智能睡眠監測器.png",
        "品牌": "searchingc",
        "name": "Reston 智能睡眠監測器",
        "功能": "非穿戴式的智能睡眠監測器\r\r\n只需鋪在床上就能通過醫療級的超薄傳感器\r\r\n採集心率、呼吸率、翻身、離床等數據\r\r\n睡眠質量分析\r\r\n睡眠專家指導\r\r\n通過藍牙傳遞到iphone手機上\r\r\n可以直接查看家人的睡眠數據",
        "特色": "檢測睡眠、記錄睡眠和分析睡眠",
        "適用族群": "老少咸宜皆可",
        "price": 6716,
        "產品資訊連結": "https://searchingc.com/collections/reston/",
        "like" : 0
    },
    {
        "id": 8,
        "category": 1,
        "img": "media/goods/HEALTH_searchingc_ 抗鼻鼾耳塞.png",
        "品牌": "searchingc",
        "name": "QuietOn Sleep \r\r\n主動降噪 抗鼻鼾耳塞",
        "功能": "主動降噪功能，可消除打鼾聲和其他環境低頻率噪音\r\r\n能有效降低 低頻率噪音，如飛機發動機、施工現場、背景噪聲等等\r\r\n具備兩種模式：靜音模式（開啟主動降噪）和 聽力模式（關閉主動降噪），按下按鈕在兩種模式之間切換",
        "特色": "可有效阻擋干擾聲波，如打鼾和機艙噪音，提供真正的寧靜",
        "適用族群": "適合各種場合，包括睡眠、身邊人打鼾、旅途、工作、坐飛機或任何嘈吵環境",
        "price": 6916,
        "產品資訊連結": "https://searchingc.com/collections/quieton-sleep/",
        "like" : 0
    },
    {
        "id": 9,
        "category": 1,
        "img": "media/goods/HEALTH_城市家居_好眠智慧枕.png",
        "品牌": "城市家居",
        "name": "SUMMER好眠智慧枕",
        "功能": "Outlast太空科技纖維、智慧調溫功能\r\r\n100%純棉加厚表布、可拆洗\r\r\n三層獨立式設計，享受五種高度變化組合\r\r\n側睡專用，特殊圓弧造型服貼設計",
        "特色": "智慧調溫功能",
        "適用族群": "老少咸宜皆可",
        "price": 2980,
        "產品資訊連結": "https://www.chung-yo.com/Product/266571",
        "like" : 0
    },
    {
        "id": 10,
        "category": 2,
        "img": "media/goods/Rehabilitation_長業企業_E-bot Pro 高畫質遠近型擴視機.png",
        "品牌": "長業企業",
        "name": "E-bot Pro 高畫質遠近型擴視機",
        "功能": "閱讀時鏡頭全自動操作。\r\r\n人員完全不用移動書本或鏡頭。\r\r\n此功能將整個頁面自頭到尾的掃描。\r\r\nOCR辨識系統：內建多國文字(含中文)辨識，無需再另行安裝。\r\r\n 亮度照明：自動感應式。\r\r\n可依環境調整亮度。",
        "特色": "可辨識中文及多國文字，電動鏡頭，可連結平板電腦、高畫質螢幕、PC，高畫質影像",
        "適用族群": "低視能者；\r\r\n銀髮族",
        "price": 125000,
        "產品資訊連結": "https://newrepat.sfaa.gov.tw/home/pavs/product/detail/2c90e4c76e7cc273016e7cc3ba5012d1",
        "like" : 0
    },
    {
        "id": 11,
        "category": 2,
        "img": "media/goods/Rehabilitation_Mimitakara耳寶_數位8頻深耳道式助聽器-C1R.png",
        "品牌": "Mimitakara耳寶",
        "name": "數位8頻深耳道式助聽器-C1R",
        "功能": "電池式設計，方便立即使用\r\r\n數位音質，打造客製化的聲音，降噪性能好 \r\r\n第一等級醫療器材，符合資格者可取得B款助聽器補助",
        "特色": "解決弱聽障礙",
        "適用族群": "適用於輕、中度聽損、銀髮族",
        "price": 29800,
        "產品資訊連結": "https://www.digibionic.com/Mimitakara%E8%80%B3%E5%AF%B6%E9%9B%B2%E7%AB%AF%E6%95%B8%E4%BD%8D8%E9%A0%BB%E6%B7%B1%E8%80%B3%E9%81%93%E5%BC%8F%E5%8A%A9%E8%81%BD%E5%99%A8-%E5%8F%B3",
        "like" : 0
    },
    {
        "id": 12,
        "category": 3,
        "img": "media/goods/Environmental_尚朋堂_超音波清洗機UC-600L.png",
        "品牌": "尚朋堂",
        "name": "超音波清洗機UC-600L",
        "功能": "LCD顯示控制狀態\r\r\n9分鐘定時關機\r\r\n半透明上蓋 可見清洗運作\r\r\n適合清洗手錶、眼鏡、金飾、假牙等產品",
        "特色": "清洗手錶、眼鏡、金飾、假牙等產品",
        "適用族群": "老少咸宜皆可",
        "price": "2,320",
        "產品資訊連結": "https://www.books.com.tw/products/N011215592?utm_source=linkedge2011&utm_medium=ap-books&utm_content=recommend&utm_campaign=ap-201910",
        "like" : 0
    },
    {
        "id": 13,
        "category": 3,
        "img": "media/goods/Environmental_Ashmore_小王子超音波清洗機.png",
        "品牌": "Ashmore",
        "name": "小王子超音波清洗機",
        "功能": "特有T-空氣聲波透析技術，實現98％潔淨率\r\r\n乳化分離，3分鐘快速洗淨等效果\r\r\n無感輕音，悄悄清洗\r\r\n小巧無需收納，放哪都不佔位\r\r\n304不銹鋼內腔，符合國家食品級​​標準，抗腐蝕",
        "特色": "無感輕音\r\r\n多用途清洗",
        "適用族群": "老少咸宜皆可",
        "price": "1970",
        "產品資訊連結": "https://tw.searchingc.com/collections/ashmore/?utm_source=SC.TW_old&utm_medium=blog_post",
        "like" : 0
    },
    {
        "id": 14,
        "category": 3,
        "img": "media/goods/Environmental_TorriiSonic_超音波清洗蛋.png",
        "品牌": "TorriiSonic",
        "name": "超音波清洗蛋",
        "功能": "以超聲波原理清洗物件，徹底震出污垢\r\r\n用途廣泛，可清洗眼鏡、手飾、疏果、衣服、內衣等\r\r\nUSB插頭，可插行動電源使用\r\r\n體積細小，可攜帶旅行或出差",
        "特色": "可清洗飾物、眼鏡、衣物得物品\r\r\n連接電源直接使用，旅遊出差坐飛機可寄倉",
        "適用族群": "老少咸宜皆可",
        "price": "1050",
        "產品資訊連結": "https://tw.searchingc.com/collections/torriisonic/?utm_source=SC.TW_old&utm_medium=blog_post",
        "like" : 0
    },
    {
        "id": 15,
        "category": 3,
        "img": "media/goods/Environmental_LG樂金_PuriCare™超淨化大白空氣清淨機.png",
        "品牌": "LG樂金",
        "name": "PuriCare™\r\r\n超淨化大白空氣清淨機",
        "功能": "Wi-Fi遠端監控遙控\r\r\nAPP貼心主動通知\r\r\n四色燈號清楚顯示空氣汙染程\r\r\n隨時把握空氣品質三重高效濾網離子淨化系統",
        "特色": "空氣品質監測系統\r\r\nApp空氣監控",
        "適用族群": "老少咸宜皆可",
        "price": "14900",
        "產品資訊連結": "https://www.etmall.com.tw/i/2639220",
        "like" : 0
    },
    {
        "id": 16,
        "category": 3,
        "img": "media/goods/Environmental_美國Honeywell_智慧淨化抗敏空氣清淨機.png",
        "品牌": "美國Honeywell",
        "name": "智慧淨化抗敏空氣清淨機",
        "功能": "直流變頻馬達：省電又靜音 \r\r\nTrue HEPA濾心 : 有效降低過敏原的污染 \r\r\n智能偵測模式\r\r\n智慧定時功能：另有2/4/8小時自動開關設定\r\r\n兒童安全鎖：三秒操作、安全又便利",
        "特色": "空氣品質監測系統\r\r\n 濾心更換提醒\r\r\n 便利滾輪",
        "適用族群": "老少咸宜皆可",
        "price": "19900",
        "產品資訊連結": "https://www.rakuten.com.tw/shop/bestgo/product/100000000056993/?scid=rafop-gs949_3C_genre&utm_source=tagtoo&utm_medium=cpc&utm_term=1007:66:20020077777&utm_campaign=tagtoo&utm_content=tagtoo&pr=d79a19ad0d3b61e1&gid=2418ddb67fffc8b6b480a4eea8bf8bcc",
        "like" : 0
    },
    {
        "id": 17,
        "category": 3,
        "img": "media/goods/Environmental_SHARP夏普_除菌離子空氣清淨機.png",
        "品牌": "SHARP夏普",
        "name": "除菌離子空氣清淨機",
        "功能": "高濃度自動除菌離子25000，空氣淨化除菌脫臭\r\r\n四大自動感應偵測 (PM2.5/灰塵/異味/亮度)\r\r\nLED空氣品質指示燈；PM2.5數值顯示，空氣品質一目瞭然\r\r\n淋浴式空氣清淨行程",
        "特色": "空氣品質監測系統",
        "適用族群": "老少咸宜皆可",
        "price": "17900",
        "產品資訊連結": "https://www.rakuten.com.tw/shop/3bjj/product/AFP-J60T-W/?scid=rafop-gs949_3C_genre&utm_source=tagtoo&utm_medium=cpc&utm_term=1007:66:20020077777&utm_campaign=tagtoo&utm_content=tagtoo&pr=d79a19ad0d3b61e1&gid=0ee154f713e24198be8f5a5a4eb96a00",
        "like" : 0
    },
    {
        "id": 18,
        "category": 3,
        "img": "media/goods/Environmental_得意家電_廚餘處理機 Pro.png",
        "品牌": "【得意家電】\r\r\n美國InSinkErator",
        "name": "廚餘處理機 Pro",
        "功能": "擁有1HP 的超強馬力，獨家的降噪技術更讓機器在運轉時幾乎沒有聲響，相信能為一般家庭打造更專業的廚房衛生處理系統。\r\r\n\r\r\n自動逆轉裝置可以預防堆積太多廚餘造成的卡死狀況",
        "特色": "減震降噪技術\r\r\n自動逆轉裝置",
        "適用族群": "老少咸宜皆可",
        "price": "35000",
        "產品資訊連結": "https://www.rakuten.com.tw/shop/der-yi/product/HFG1CTCGJ/?scid=rafp-f133_3C_tcpa&gid=Pn-mEspSMAACQcMKpEaOpVw%3D%3D.99",
        "like" : 0
    },
    {
        "id": 19,
        "category": 3,
        "img": "media/goods/Environmental_克立爾 cleaair_家用環保廚餘處理機.png",
        "品牌": "克立爾 cleaair",
        "name": "家用環保廚餘處理機",
        "功能": "四級研磨技術，廚餘微粒小於3mm\r\r\n雙層ABS隔音罩，降低研磨噪音\r\r\n合金旋轉錘，無刀片設計\r\r\n加強研磨腔防腐蝕處理\r\r\n高扭矩超靜音交流驅動馬達高穩定",
        "特色": "交流驅動馬達\r\r\n四級研磨技術\r\r\n防腐蝕處理",
        "適用族群": "老少咸宜皆可",
        "price": "2,800",
        "產品資訊連結": "https://shopee.tw/product/1521857/3131746209?utm_source=an_16142330000&utm_medium=affiliates&utm_content=POyiPxJSMAACQZNt~EwPheA%3D%3D.99",
        "like" : 0
    },
    {
        "id": 20,
        "category": 3,
        "img": "media/goods/Environmental_島產業_PCL-31-BWR 家庭用廚餘處理機.png",
        "品牌": "島產業",
        "name": "PCL-31-BWR \r\r\n家庭用廚餘處理機",
        "功能": "不需特別分類，牙籤魚骨一次解決\r\r\n溫風乾燥噪音小\r\r\n用活性炭特殊濾網，除臭效果一流\r\r\n先把內層拿出，套上瀝水網後倒入廚餘，輕鬆瀝水不髒手",
        "特色": "獨特除臭濾網\r\r\n處理不髒手",
        "適用族群": "老少咸宜皆可",
        "price": "5591",
        "產品資訊連結": "https://www.letao.com.tw/jpselection/item.php?it_id=177&path_id=eyJjYSI6IjYiLCJzdWIiOiIxNSIsImZpZyI6IjE3NyIsImJyYW5kIjoiNDEiLCJpdGVtX2lkIjpudWxsfQ%3D%3D&utm_source=feebee&utm_medium=web&utm_campaign=feebee_web",
        "like" : 0
    },
    {
        "id": 21,
        "category": 4,
        "img": "media/goods/Other_Sony_自動駕駛車.png",
        "品牌": "Sony",
        "name": "自動駕駛車",
        "功能": "善用成像和感測技術以支援自動駕駛，車體內外設有 33 種感測器，包括支援 HDR 的 CMOS 圖像傳感器，以感測道路與物體以及顏色辨識。日夜間視覺辨識的固態 LiDAR 以及檢測速度與距離的感應雷達",
        "特色": "成像和感測技術LiDAR 以及檢測速度與距離的感應雷達",
        "適用族群": "老少咸宜皆可",
        "price": "$$$",
        "產品資訊連結": "https://www.storm.mg/article/2153830",
        "like" : 0
    },
    {
        "id": 22,
        "category": 4,
        "img": "media/goods/Other_Bosch 博世_透明遮陽板.png",
        "品牌": "Bosch 博世",
        "name": "透明遮陽板",
        "功能": "透過臉部辨識與追蹤軟體辨識駕駛者正確位置，將會照射到駕駛眼睛部分光線自動調暗，其餘不影響駕駛視線的地方仍維持全透明狀態",
        "特色": "以透明的 LED 面板取代遮陽板，在 AI 計算之下，Virtual Visor 只會在眼睛範圍內產生陰影、減少眩光",
        "適用族群": "老少咸宜皆可",
        "price": "$$$",
        "產品資訊連結": "https://today.line.me/tw/v2/article/OvDqKD",
        "like" : 0
    },
    {
        "id": 23,
        "category": 4,
        "img": "media/goods/Other_Roland_直播器材.png",
        "品牌": "Roland",
        "name": "直播器材",
        "功能": "機台擁有兩個 USB Micro-B 插口以充電與連接手機；一個組合式麥克風插孔，支援 XLR 和 1/4 英寸 TRS 端子；兩個用於耳機和樂器的標準立體聲插孔。機台控制鍵除了基本的四個音量與麥克風旋鈕，還有 10 個按鈕用以切換畫面、收看留言、加入預存的影片與文檔等等",
        "特色": "啟動聲音效果和視頻片段可移動實時流媒體",
        "適用族群": "老少咸宜皆可",
        "price": "$$$",
        "產品資訊連結": "http://www.tool-tour.tw/?p=9739",
        "like" : 0
    },
    {
        "id": 24,
        "category": 2,
        "img": "media/goods/Rehabilitation_Opro9 SmartDiaper_智慧尿濕感知器.png",
        "品牌": "Opro9 SmartDiaper",
        "name": "智慧尿濕感知器",
        "功能": "會在使用者尿濕的時候提醒妳,尿濕了,該為使用者換尿布,透過智慧型手機,對使用者的狀況即時掌握。透過APP,記錄寶寶尿濕次數,可以知道寶寶的代謝健康狀況,特殊的防丟提醒。",
        "特色": "即時記錄小便次數、時間及尿布更換次數 手機可最多可連線5台SmartDiaper 好撕好黏，位置調整方便 雲端大數據整合，協助如廁訓練",
        "適用族群": "老少咸宜皆可",
        "price": "1,490",
        "產品資訊連結": "http://innovation.itmonth.org.tw/product_detail.php?pid=2516&uid=1007&year=2016&PHPSESSID=jer42tau58011pcruullf11dh3#tabs2",
        "like" : 0
    },
    {
        "id": 25,
        "category": 2,
        "img": "media/goods/Rehabilitation_NorthFox北狐_USB智能隨身電熱毯 加熱毯.png",
        "品牌": "NorthFox北狐",
        "name": "USB智能隨身電熱毯 加熱毯",
        "功能": "USB接頭設計，加熱超便利 走到哪，溫暖跟到哪 雙面保暖刷毛毛毯，觸感柔軟 快速均勻加熱 加熱片輕鬆拿取，毛毯洗滌方便",
        "特色": "USB接頭設計 快速均勻加熱",
        "適用族群": "老少咸宜皆可",
        "price": "1,500",
        "產品資訊連結": "http://www.habitz-medtech.com/product/northfox%e5%8c%97%e7%8b%90-usb%e6%99%ba%e8%83%bd%e9%9a%a8%e8%ba%ab%e9%9b%bb%e7%86%b1%e6%af%af-%e5%8a%a0%e7%86%b1%e6%af%af/",
        "like" : 0
    },
    {
        "id": 26,
        "category": 2,
        "img": "media/goods/Rehabilitation_Mr.Pill藥管家_智慧管理藥盒.png",
        "品牌": "Mr.Pill藥管家",
        "name": "智慧管理藥盒",
        "功能": "一天24小時全時關注，有效提醒，謹慎管理 聲光雙重提醒，取藥防呆設計，避免忘記吃藥 免網路和APP 簡單一鍵取藥",
        "特色": "電子鬧鈴藥盒",
        "適用族群": "老少咸宜皆可",
        "price": "2,980",
        "產品資訊連結": "https://shopping.udn.com/mall/cus/cat/Cc1c02.do?dc_cateid_0=N_006_009_003_004&dc_cargxuid_0=U010378469&gclid=EAIaIQobChMIyIiU_t6c7QIVxF1gCh1snwvyEAQYBCABEgLBQPD_BwE",
        "like" : 0
    },
    {
        "id": 27,
        "category": 2,
        "img": "media/goods/Rehabilitation_晁禾醫療_DIEGO 虛擬實境＋動態重力輔助.png",
        "品牌": "晁禾醫療",
        "name": "DIEGO 虛擬實境＋動態重力輔助",
        "功能": "獨家智能動態重力輔助 擴增實境遊戲 單側與雙側協調訓練 IGC系統-智能重力補償系統",
        "特色": "IGC系統 智能懸臂系統 改善肩臂疼痛受限與神經動作復健",
        "適用族群": "有肩臂疼痛受限與神經動作復健者",
        "price": "$$$",
        "產品資訊連結": "http://www.habitz-medtech.com/product/diego-%e8%99%9b%e6%93%ac%e5%af%a6%e5%a2%83%ef%bc%8b%e5%8b%95%e6%85%8b%e9%87%8d%e5%8a%9b%e8%bc%94%e5%8a%a9/",
        "like" : 0
    },
    {
        "id": 28,
        "category": 2,
        "img": "media/goods/Rehabilitation_晁禾醫療_HAND OF HOPE 希望之手.png",
        "品牌": "晁禾醫療",
        "name": "HAND OF HOPE 希望之手",
        "功能": "骨骼肌的自動性啟動及收縮能力 肌肉的控制和協調 放鬆肌肉 增進腦部控制運動的主動性 控制異常的肌肉活動 能持續強化患者腦部與手掌肌肉的控制及反應",
        "特色": "EMG＋VR＋外骨骼動作系統 中樞動作意念 運動神經元傳導 前臂肌電偵測 外骨骼動作輔助 神經正向回饋",
        "適用族群": "中風、脊髓損傷或者手部受損導致的手部肌肉 功能損失的患者 難以自發激活，維持或者控制手部運動的患者 上肢運動不協調的患者",
        "price": "$$$",
        "產品資訊連結": "http://www.habitz-medtech.com/product/hand-of-hope-%e5%b8%8c%e6%9c%9b%e4%b9%8b%e6%89%8b/",
        "like" : 0
    },
    {
        "id": 29,
        "category": 2,
        "img": "media/goods/Rehabilitation_晁禾醫療_PABLO 無線加速規陀螺儀.png",
        "品牌": "晁禾醫療",
        "name": "PABLO 無線加速規陀螺儀",
        "功能": "智能上肢動作分析訓練設備，結合無線藍芽、陀螺儀、加速規與壓力感測技術，數位化紀錄個案關節角度與力量變化，解決傳統無法追蹤及視覺化之限制，直覺反饋治療成效。",
        "特色": "力量、協調、步態評估與訓練",
        "適用族群": "神經損傷、骨科、小兒、衰弱症者",
        "price": "$$$",
        "產品資訊連結": "http://www.habitz-medtech.com/product/pablo-%e7%84%a1%e7%b7%9a%e5%8a%a0%e9%80%9f%e8%a6%8f%e9%99%80%e8%9e%ba%e5%84%80/",
        "like" : 0
    }
]